doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            money: 'LegacyFighter\Cabs\Money\MoneyType'
            miles: 'LegacyFighter\Cabs\Loyalty\MilesType'
            distance: 'LegacyFighter\Cabs\Distance\DistanceType'
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            LegacyFighter:
                is_bundle: false
                dir: '%kernel.project_dir%/src'
                prefix: 'LegacyFighter\Cabs'
                alias: LegacyFighter
