services:
  _defaults:
    autowire: true
    autoconfigure: true

  LegacyFighter\Cabs\Tests\Common\Fixtures:
    public: true

  LegacyFighter\Cabs\Tests\Common\AddressFixture: ~
  LegacyFighter\Cabs\Tests\Common\AwardsAccountFixture: ~
  LegacyFighter\Cabs\Tests\Common\CarTypeFixture: ~
  LegacyFighter\Cabs\Tests\Common\ClaimFixture: ~
  LegacyFighter\Cabs\Tests\Common\ClientFixture: ~
  LegacyFighter\Cabs\Tests\Common\DriverFixture: ~
  LegacyFighter\Cabs\Tests\Common\RideFixture: ~
  LegacyFighter\Cabs\Tests\Common\StubbedTransitPrice: ~
  LegacyFighter\Cabs\Tests\Common\TransitFixture: ~

  LegacyFighter\Cabs\Service\GeocodingService:
    class: LegacyFighter\Cabs\Tests\Double\FakeGeocodingService

  LegacyFighter\Cabs\Config\AppProperties:
    class: LegacyFighter\Cabs\Tests\Double\FakeAppProperties

  LegacyFighter\Cabs\Common\Clock:
    class: LegacyFighter\Cabs\Tests\Common\FixedClock

  LegacyFighter\Cabs\TransitAnalyzer\PopulateGraphService:
    public: true

  LegacyFighter\Cabs\Repair\Api\RepairProcess:
    public: true

  LegacyFighter\Cabs\Repair\Api\ContractManager:
    public: true

  LegacyFighter\Cabs\Contracts\Application\Editor\DocumentEditor:
    public: true

  LegacyFighter\Cabs\Contracts\Application\Acme\Dynamic\DocumentResourceManager:
    public: true

  LegacyFighter\Cabs\Contracts\Legacy\UserRepository:
    public: true

  LegacyFighter\Cabs\Contracts\Application\Acme\Straigthforward\AcmeContractProcessBasedOnStraightforwardDocumentModel:
    public: true
