services:
  _defaults:
    autowire: true
    autoconfigure: true

  LegacyFighter\Cabs\Tests\Common\Fixtures:
    public: true

  LegacyFighter\Cabs\Service\GeocodingService:
    class: LegacyFighter\Cabs\Tests\Double\FakeGeocodingService
